default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sexplus_development
  username: sexplus
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: sexplus_test
  username: sexplus
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: sexplus_production
  username: sexplus
  password: <%= ENV['SEXPLUS_DATABASE_PASSWORD'] %>
