# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55d39db68357922ae7b8b813a4222b3d8d7baa8f40d86446cb500934977f83516049f34a3d70f388622a9da439698989ae75ae917ece94719b817442a65f9592

test:
  secret_key_base: d91afb89f0fd9858e528f7dc2d389a382bc89efbc896e13d0cf84fa56079ed3a454b18071eb761162c861ff76d935b57302e2c7f84595ea1f1d5c01e78e6f5ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
